# Generated by Django 2.2.28 on 2023-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField()),
                ('value2', models.BigIntegerField()),
                ('valuew', models.BigIntegerField()),
            ],
        ),
    ]
