# Generated by Django 2.2.28 on 2023-05-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newmo_rojo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate', models.EmailField(max_length=254)),
            ],
        ),
    ]
